export const mutualChatData = [
  {
    _id: '1',
    identifier: 'chat1',
    senderId: 'user1',
    senderName: 'Alice',
    receiverId: 'user2',
    receiverName: 'Bob',
    message: 'Hey Bob! How’s it going?',
    timestamp: new Date('2024-10-29T10:00:00Z'),
    read: true,
  },
  {
    _id: '2',
    identifier: 'chat1',
    senderId: 'user2',
    senderName: 'Bob',
    receiverId: 'user1',
    receiverName: 'Alice',
    message: 'Hey Alice! I’m good, just working on some projects.',
    timestamp: new Date('2024-10-29T10:02:00Z'),
    read: true,
  },
  {
    _id: '3',
    identifier: 'chat1',
    senderId: 'user1',
    senderName: 'Alice',
    receiverId: 'user2',
    receiverName: 'Bob',
    message: 'Nice! What project are you working on?',
    timestamp: new Date('2024-10-29T10:05:00Z'),
    read: false,
  },
  {
    _id: '4',
    identifier: 'chat1',
    senderId: 'user2',
    senderName: 'Bob',
    receiverId: 'user1',
    receiverName: 'Alice',
    message: 'I’m building a chat application in React Native.',
    timestamp: new Date('2024-10-30T10:07:00Z'),
    read: false,
  },
  {
    _id: '5',
    identifier: 'chat1',
    senderId: 'user1',
    senderName: 'Alice',
    receiverId: 'user2',
    receiverName: 'Bob',
    message: 'Oh, that’s cool! I’d love to see it sometime.',
    timestamp: new Date('2024-10-30T10:10:00Z'),
    read: false,
  },
  {
    _id: '6',
    identifier: 'chat1',
    senderId: 'user2',
    senderName: 'Bob',
    receiverId: 'user1',
    receiverName: 'Alice',
    message: 'Definitely! Let me know when you’re free.',
    timestamp: new Date('2024-10-30T10:12:00Z'),
    read: false,
  },
  {
    _id: '7',
    identifier: 'chat1',
    senderId: 'user1',
    senderName: 'Alice',
    receiverId: 'user2',
    receiverName: 'Bob',
    message: 'Will do! How far along is it?',
    timestamp: new Date('2024-10-30T10:15:00Z'),
    read: false,
  },
  {
    _id: '8',
    identifier: 'chat1',
    senderId: 'user2',
    senderName: 'Bob',
    receiverId: 'user1',
    receiverName: 'Alice',
    message:
      'About halfway there. Still working on the UI and message storage.',
    timestamp: new Date('2024-10-30T10:18:00Z'),
    read: false,
  },
  {
    _id: '9',
    identifier: 'chat1',
    senderId: 'user1',
    senderName: 'Alice',
    receiverId: 'user2',
    receiverName: 'Bob',
    message: 'Sounds like it’s coming along well!',
    timestamp: new Date('2024-10-30T10:20:00Z'),
    read: false,
  },
  {
    _id: '10',
    identifier: 'chat1',
    senderId: 'user2',
    senderName: 'Bob',
    receiverId: 'user1',
    receiverName: 'Alice',
    message: 'Thanks! Hoping to wrap it up by next week.',
    timestamp: new Date('2024-10-30T10:23:00Z'),
    read: false,
  },
  {
    _id: '11',
    identifier: 'chat1',
    senderId: 'user1',
    senderName: 'Alice',
    receiverId: 'user2',
    receiverName: 'Bob',
    message: 'That’s quick! Let me know if you need any help.',
    timestamp: new Date('2024-10-30T10:25:00Z'),
    read: false,
  },
  {
    _id: '12',
    identifier: 'chat1',
    senderId: 'user2',
    senderName: 'Bob',
    receiverId: 'user1',
    receiverName: 'Alice',
    message: 'Will do! Maybe you could help test it later?',
    timestamp: new Date('2024-10-30T10:28:00Z'),
    read: false,
  },
  {
    _id: '13',
    identifier: 'chat1',
    senderId: 'user1',
    senderName: 'Alice',
    receiverId: 'user2',
    receiverName: 'Bob',
    message: 'For sure! Testing is my thing.',
    timestamp: new Date('2024-10-30T10:30:00Z'),
    read: false,
  },
  {
    _id: '14',
    identifier: 'chat1',
    senderId: 'user2',
    senderName: 'Bob',
    receiverId: 'user1',
    receiverName: 'Alice',
    message: 'Awesome! I appreciate it.',
    timestamp: new Date('2024-10-30T10:33:00Z'),
    read: false,
  },
  {
    _id: '15',
    identifier: 'chat1',
    senderId: 'user1',
    senderName: 'Alice',
    receiverId: 'user2',
    receiverName: 'Bob',
    message: 'Anytime! When’s the first testing round?',
    timestamp: new Date('2024-10-30T10:35:00Z'),
    read: false,
  },
  {
    _id: '16',
    identifier: 'chat1',
    senderId: 'user2',
    senderName: 'Bob',
    receiverId: 'user1',
    receiverName: 'Alice',
    message: 'Probably in two days. I’ll message you the details.',
    timestamp: new Date('2024-10-30T10:38:00Z'),
    read: false,
  },
  {
    _id: '17',
    identifier: 'chat1',
    senderId: 'user1',
    senderName: 'Alice',
    receiverId: 'user2',
    receiverName: 'Bob',
    message: 'Cool, I’ll make sure I’m available.',
    timestamp: new Date('2024-10-30T10:40:00Z'),
    read: false,
  },
  {
    _id: '18',
    identifier: 'chat1',
    senderId: 'user2',
    senderName: 'Bob',
    receiverId: 'user1',
    receiverName: 'Alice',
    message: 'Thanks a lot, Alice!',
    timestamp: new Date('2024-10-30T10:42:00Z'),
    read: false,
  },
  {
    _id: '19',
    identifier: 'chat1',
    senderId: 'user1',
    senderName: 'Alice',
    receiverId: 'user2',
    receiverName: 'Bob',
    message: 'No problem! Looking forward to it.',
    timestamp: new Date('2024-10-31T10:45:00Z'),
    read: false,
  },
  {
    _id: '20',
    identifier: 'chat1',
    senderId: 'user2',
    senderName: 'Bob',
    receiverId: 'user1',
    receiverName: 'Alice',
    message: 'Me too! Catch up soon.',
    timestamp: new Date('2024-10-31T10:48:00Z'),
    read: false,
  },
];
